apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-mlops-api
  namespace: secure-mlops
  labels:
    app: secure-mlops-api

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: secure-mlops-api

  template:
    metadata:
      labels:
        app: secure-mlops-api

    spec:
      containers:
        - name: secure-mlops-api

          image: 591064574283.dkr.ecr.us-east-1.amazonaws.com/secure-mlops-platform:1.0.18

          imagePullPolicy: Always

          ports:
            - containerPort: 8000
              protocol: TCP

          envFrom:
            - configMapRef:
                name: secure-mlops-config

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3