apiVersion: v1
kind: Service
metadata:
  name: secure-mlops-service
  namespace: secure-mlops

spec:
  type: LoadBalancer

  selector:
    app: secure-mlops-api

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000